# Generated by Django 6.0.4 on 2026-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_class_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='students.student'),
        ),
    ]
